#!/bin/bash

# Get the IP address of the machine
ip_address=$(hostname -I | awk '{print $1}')

# Define the ThingsBoard default port (8080)
port=8080

# Construct the URL
url="http://$ip_address:$port"

# Print the ThingsBoard URL
echo "ThingsBoard instance: $url"